name: Deploy to Github Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build ssg blog
        run: npm run build

      - name: Push built blog to gh-pages branch
        uses: s0/git-publish-subdir-action@develop
        env:
         REPO: self
         BRANCH: gh-pages
         FOLDER: build
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
