name: PushToGhPages

on:
  push:
    branches:
      - main
    paths:
      - 'static/'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: Build ssg blog
        run: npm run dev
      - name: Upload ssg blog
        uses: actions/upload-artifact@v3.1.2
        with:
          name: blog-build
          path: build/